# Full Appveyor schema: https://www.appveyor.com/docs/appveyor-yml/

# An empty .appveyor.yml file defaults to MSBuild
# https://ci.appveyor.com/project/claremacrae/ci-playground/builds/25964280

# https://www.appveyor.com/docs/lang/cpp/
#image:
#  - Visual Studio 2015
#  - Visual Studio 2017
#  - Visual Studio 2019

BUILD_ENVIRONMENT: windows # Use windows cmd, unless overridden in the matrix

# https://www.appveyor.com/docs/build-environment/#using-multiple-images-for-the-same-build
environment:
  matrix:
    - TARGET: vs2015
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - TARGET: vs2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - TARGET: vs2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

# TODO Try using this to build multiple configurations, including mingw:
# https://github.com/gabime/spdlog/blob/v1.x/appveyor.yml

# TODO Try using something like this to build with cygwin
# C:\Users\Clare\.CLion2019.1\system\cygwin_cmake\bin\cmake.exe -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /cygdrive/d/Users/Clare/Documents/Programming/github/ApprovalTests/ci_playground/hello_world
# https://github.com/libyal/libmsiecf/blob/master/appveyor.yml - looks good
# https://github.com/ALaDyn/piccante/blob/master/appveyor.yml

# -------------------------------------------------------------------
# The order of available build steps in Appveyor:
# https://www.appveyor.com/docs/build-configuration/#build-pipeline

init:
  - echo init - runs before cloning

install:
  - echo install - runs after cloning

build_script:
  - cmd: if [%TARGET%]==[windows] (
      echo build_script &&
      mkdir .build &&
      cd .build &&
      cmake .. &&
      cmake --build . )

test_script:
  - echo test_script
  # ctest --verbose

# Notifications are best controlled via Appveyor preferences
